---
- name: Download file on jumphost
  hosts: jumphost

  tasks:
  - name: get file from url
    get_url:
      url: "{{file_url}}"
      dest: "/tmp/target_file.txt"

- hosts: all:!jumphost
  gather_facts: no
  tasks:
    - synchronize:
        src: /tmp/target_file.txt
        dest: /tmp/target_file.txt
        rsync_opts: --rsh "ssh -o PasswordAuthentication=no -i {{JH_SSH_PRIVATE_KEY}}"
      delegate_to: jumphost

