---
- name: Download file on jumphost
  hosts: jumphost

  tasks:
  - name: get file from url
    get_url:
      url: "{file_url}"
      dest: "/tmp/target_file.txt"

  - name: Transfer file from jumphost to yellowzones
    synchronize:
      src: /tmp/target_file.txt
      dest: /tmp/target_file.txt
      mode: pull
    delegate_to: 	yellowzone


