---
- name: Download file on jumphost
  hosts: jumphost
  tasks:
  - name: get file from url
    get_url:
      url: "{{file_url}}"
      dest: "/tmp/target_file.txt"

  - name: Fetch the file from the mwiapp01 to master
    run_once: yes
    fetch: 
      src: "/tmp/target_file.txt"
      dest: "/tmp/target_file.txt"
      flat: yes
    

- hosts: all:!jumphost
  gather_facts: no
  tasks:
    - copy:
        src: /tmp/target_file.txt
        dest: /tmp/target_file.txt



